#ifndef __VIRT_H
#define __VIRT_H

#define VIRTIO_BEGIN_ADDRESS 0x10001000ULL
#define VIRTIO_COUNT 8
#define VIRTIO_ADDRESS_SPACE_SIZE 0x01FF

#define MMIO_BEGIN_VA 0xFFFFFFC080000000ULL
#define MMIO_END_VA ((MMIO_BEGIN_VA) + (VIRTIO_COUNT) * (PAGE_SIZE))

#define MMIO_VA_OFFSET (MMIO_BEGIN_VA - VIRTIO_BEGIN_ADDRESS)

#endif