#!/bin/bash
set -e

for s in "$@"; do
	name="$(echo "$s/" | cut -f1 -d/)"
	pri="$(echo "$s/" | cut -f2 -d/)"
	if [ -z "$name" ]; then
		out="$out ENV_CREATE($pri);"
	elif [ -z "$pri" ]; then
		out="$out ENV_CREATE(test_$name);"
	else
		out="$out ENV_CREATE_PRIORITY(test_$name, $pri);"
	fi
done

# shellcheck disable=2028
echo 'void schedule(int yield);
void riscv64_init(u_reg_t hart_id, void *dtb_address) {
	printk("init.c:\triscv64_init() is called\n");

	exception_init();

    riscv64_detect_memory();
    riscv64_vm_init();
    page_init();

	kmalloc_init();

	env_init();

	device_tree_init(dtb_address);

    plic_init();

    virtio_init();

    serial_init();

	ENV_CREATE_NAME("serial", user_serial);
    ENV_CREATE_NAME("virtio", user_virtio);
	ENV_CREATE_NAME("idle", user_bare_loop);

'"$out"'

	schedule(0);
	panic("init.c:\tend of riscv64_init() reached!");
}' > include/generated/init_override.h
